name: CI

on:
  push:
    branches-ignore:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci  --ignore-scripts

      - name: Lint Affected Packages
        run: npm run lint

      - name: Build Affected Packages
        run: npm run build -ws

      - name: Execute Unit Tests
        run: npm test -ws
